# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 22:57
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_album', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=150, null=True)),
                ('descrip', models.TextField(null=True)),
                ('fecha_publicacion', models.DateField()),
                ('autor', models.TextField(max_length=150, null=True)),
                ('archivo', models.FileField(null=True, upload_to='archivos/')),
                ('usuario_creo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_imagen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CentroAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_centro_ayuda', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('direccion', models.TextField(max_length=250, null=True)),
                ('sitio_web', models.TextField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('google_maps', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateField()),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_imagen', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('categoria_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.CategoriaImagen')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesGaleriaAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_imagen', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.AlbumGaleria')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('tag_nombre', models.TextField(max_length=200)),
                ('tag_url', models.TextField(max_length=200)),
                ('icon_css', models.TextField(max_length=200)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuRedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('tag_nombre', models.TextField(max_length=200)),
                ('tag_url', models.TextField(max_length=200)),
                ('icon_css', models.TextField(max_length=200)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('resumen', ckeditor.fields.RichTextField(null=True)),
                ('fecha_creacion', models.DateField()),
                ('imagen_portada', models.ImageField(null=True, upload_to='imagenes/')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.Estado')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.CategoriaPost')),
                ('usuario_creo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoCentroAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.TextField(max_length=20)),
                ('centro_ayuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.CentroAyuda')),
            ],
        ),
        migrations.CreateModel(
            name='ZonasCentroAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.TextField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='comentariospost',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.Estado'),
        ),
        migrations.AddField(
            model_name='comentariospost',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.Post'),
        ),
        migrations.AddField(
            model_name='centroayuda',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.ZonasCentroAyuda'),
        ),
        migrations.AddField(
            model_name='categoriapost',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.Estado'),
        ),
    ]
